import React from 'react'


function SkeletonAnimation({ width, height }) {
    console.log('width', width, 'height', height);
  
    // Return the array of divs generated by Array.from
    return (
      <>
      
          <div
           
            className=
            {`
                animate-pulse
                bg-slate-200
                rounded-lg
                mb-2
              
              `}
            style={{width:width, height:height}}
          >
         
          </div>
     
      </>
    );
  }
// function SkeletonAnimation({ width, height, num }) {
//     console.log('width', width, 'height', height);
  
//     // Return the array of divs generated by Array.from
//     return (
//       <>
//         {Array.from({ length: num }, (_, index) => (
//           <div
//             key={index}
//             className=
//             {`
//                 animate-pulse
//                 bg-slate-500
//                 rounded-lg
//                 w-[${width}]
//                 h-[${height}]
//               `}
         
//           >
          
//           </div>
//         ))}
//       </>
//     );
//   }
  
export default SkeletonAnimation