'use client'
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import {cartContext} from './_context/CartContext'
import { useState } from "react";
import { ToastContainer } from 'react-toastify';

import '../node_modules/react-toastify/dist/ReactToastify.css'
const robotoFont = Roboto({
  weight:'700',
  subsets: ["latin"],
});



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart , setCart] = useState([])
  return (
    <ClerkProvider>
     <cartContext.Provider value={{cart,setCart}}>
     <html lang="en">
        <body
          className={robotoFont.className}
        >
          <Header/>
          <ToastContainer
            autoClose={2000}
          />
          {children}
          <Footer/>
        </body>
      </html>
     </cartContext.Provider>
    </ClerkProvider>

  );
}
