'use client'
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import {cartContext} from './_context/CartContext'
import {productsContext} from './_context/ProductsContext'

import { useState } from "react";
import { ToastContainer } from 'react-toastify';
import { NextUIProvider } from "@nextui-org/react";
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';
import '../node_modules/react-toastify/dist/ReactToastify.css'
import "primereact/resources/themes/lara-light-cyan/theme.css";
const robotoFont = Roboto({
  weight:'700',
  subsets: ["latin"],
});


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart , setCart] = useState([])

  const[products, setProducts] = useState({})
  return (
    <ClerkProvider>
      <productsContext.Provider value={{products,setProducts}}>
      <PrimeReactProvider >
        <cartContext.Provider value={{cart,setCart}}>
        
          <html lang="en">
              <body
                className={robotoFont.className}
              >
                <Header/>
                <ToastContainer
                  autoClose={2000}
                />
                <NextUIProvider >
                {children}
                </NextUIProvider>
              
                <Footer/>
              </body>
            </html>
    

      
        </cartContext.Provider>
        </PrimeReactProvider>
     </productsContext.Provider>
    </ClerkProvider>

  );
}
